name: Contributors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3

jobs:
  update:
    name: Update
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Run contributors script
        run: npx tsx tooling/scripts/contributors.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update contributors'
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: 'chore: update contributors'
          branch: chore/update-contributors
          base: main
          delete-branch: true
